# NUMPY NOTES

In [2]:
import numpy as np

In [74]:
print(np.version)

<module 'numpy.version' from 'C:\\Users\\uppada satwik\\AppData\\Roaming\\Python\\Python310\\site-packages\\numpy\\version.py'>


# Data types in NUMPY

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )


In [3]:


dt =np.dtype(np.int32)
print(dt)

int32


In [8]:
#int 8 ,int 16 ,int 32 ,int 64 are equivalent to i1,i2,i4,i8
dt=np.dtype('i1')
print(dt)

dt=np.dtype('i2')
print(dt)

dt=np.dtype('i4')
print(dt)

dt=np.dtype('i8')
print(dt)


int8
int16
int32
int64


endian notation

In [9]:
dt=np.dtype('>i4')
print(dt)

>i4


In [10]:
dt=np.dtype([("age",np.int8)])
print (dt)

[('age', 'i1')]


In [17]:
# APPLYING TO N DIMENTIONALA ARRRAY

a=np.array([(10),(20),(30)])
print (a)

[10 20 30]


In [24]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(a)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


# Min dimensions

In [25]:
#min dimensions
a=np.array([1,2,3,4,5],ndmin=2)
print (a)

[[1 2 3 4 5]]


# dtype parameter


In [117]:
a=np.array([[1,2,3],[3,4,5]],dtype="c")
print("complex float")
print(a)
print("--------------------")
a=np.array([[1,2,3],[3,4,5]],dtype=complex)
print("complex")
print(a)
print("--------------------")
a=np.array([[1,2,3],[3,4,5]],dtype="S")
print("String")
print(a)
print("--------------------")
a=np.array([[1,2,3],[3,4,5]],dtype="i")
print("integer")
print(a)

print("--------------------")
a=np.array([[1,2,3],[3,4,5]],dtype="b")
print("boolean")
print(a)
print("--------------------")
# a=np.array([[1,2,3],[3,4,5]],dtype="u")
# print(a)
# print("--------------------")
a=np.array([[1,2,3],[3,4,5]],dtype="m")
print("timedelta")
print(a)
print("--------------------")
# a=np.array([[1,2,3],[3,4,5]],dtype="M")
# print(a)
# print("--------------------")
a=np.array([[1,2,3],[3,4,5]],dtype="O")
print("object")
print(a)
print("--------------------")

a=np.array([[1,2,3],[3,4,5]],dtype="U")
print("Unicode string")
print(a)
print("--------------------")
# a=np.array([[1,2,3],[3,4,5]],dtype="V")
# print(a)







complex float
[[b'1' b'2' b'3']
 [b'3' b'4' b'5']]
--------------------
complex
[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]
--------------------
String
[[b'1' b'2' b'3']
 [b'3' b'4' b'5']]
--------------------
integer
[[1 2 3]
 [3 4 5]]
--------------------
boolean
[[1 2 3]
 [3 4 5]]
--------------------
timedelta
[[1 2 3]
 [3 4 5]]
--------------------
object
[[1 2 3]
 [3 4 5]]
--------------------
Unicode string
[['1' '2' '3']
 ['3' '4' '5']]
--------------------


# Arrays

In [75]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [76]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [88]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print (arr)
print(arr[0,0])
print(arr[0,1])
print(arr[0,2])
print(arr[0,3])
print("\n")
print(arr[1,0])
print(arr[1,1])
print(arr[1,2])
print(arr[1,3])

[[1 2 3 4]
 [5 6 7 8]]
1
2
3
4


5
6
7
8


In [92]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6 ]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])# prints 6  as output
# first 0 will select first array in whole set
#then 1 will select second array in that first set
#then 2 refers to third element in that array

6


In [96]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])
print('Second Last element from 2nd dim: ', arr[1, -2])

Last element from 2nd dim:  10
Second Last element from 2nd dim:  9


slicing

In [104]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[1:5])
print(arr[:4])
print(arr[-3:-1])
print(arr[::2])# start::step


[2 3 4 5]
[1 2 3 4]
[4 5]
[1 3 5]


In [105]:
import numpy as np
arr=np.array([[1,2,3,4,5,6,7],[8,9,0,1,2,3,4]])
print(arr[1,1:4])

[9 0 1]


# Array Attributes

In [29]:
#ndarray.shape
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)

(3, 3)


In [32]:
#redefine shape of an array
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


# ndarray.ndim(arange())

In [36]:
#nd array.ndim
a=np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [38]:
b=a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


# numpy.itemsize

In [45]:
x=np.array([1,2,3,4,5],dtype=np.int8)
print(x)

[1 2 3 4 5]


In [46]:
print(x.itemsize)

1


In [48]:
x=np.array([1,2,3,4,5],dtype=np.float32)
print(x)
print(x.itemsize)

[1. 2. 3. 4. 5.]
4


# math lib

In [50]:
import math as m #importing math library

In [59]:
a=m.sqrt(81)
print(a)
b=m.floor(7.2)
print(b)
c=m.ceil(7.2)
print(c)
d=(m.sin(90))
print(d)

9.0
7
8
0.8939966636005579


In [62]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=((a-b)**2).sum()
m.sqrt(c)


5.196152422706632

# Numpy array operations

In [72]:
a=np.array([1,2,3])
b=np.array([3,4,5])
print(a+b)
print(a*b)
print(a**b)
print(a.mean())
print(b.mean())
print(a.sum())
print(b.sum())


[4 6 8]
[ 3  8 15]
[  1  16 243]
2.0
4.0
6
12
